blank_issues_enabled: false
contact_links:
  - name: 🗂️ Board do CANTEIRO
    url: https://github.com/users/mateus-vitor-ferreira-dev/projects/5
    about: Todas as tarefas, por sprint e por integrante.
